name: Deploy API to Render

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:


    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Change directory to the subfolder
      run: cd ApiProject

    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH="$PYTHONPATH:$(pwd)"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.10'

    - name: Install dependencies
      run:
        cd ApiProject|
        python -m pip install --upgrade pip
        pip install render-python

    - name: Run unit tests
      run:
        export PYTHONPATH="$PYTHONPATH:$(pwd)"
        pytest ApiProject/tests/ --maxfail=1 --disable-warnings  # Run tests and stop at the first failure


    - name: Deploy to Render
      if: success()
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        cd ApiProject
        render services update srv-ct9di9popnds73e7v66g \
          --service-type web \
          --branch master \
          --env python
